version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # Porta principal da API
    volumes:
      - ./data:/qdrant/storage  # Dados salvos no disco local
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M  # Limita RAM usada pelo container (opcional)
