version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    environment:
      - QDRANT_SERVICE_API_KEY=${QDRANT_API_KEY}
    ports:
      - "6333:6333"
    volumes:
      - ./data:/qdrant/storage
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
